import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Bodoni_Moda } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MouseMove from "@/components/common/MouseMove";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: "400",
});

const bodoniModa = Bodoni_Moda({
  variable: "--font-bodoni-moda",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ahava Yoffi ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.variable} ${bodoniModa.variable} antialiased`}
      >
        <MouseMove />
        {children}
      </body>
    </html>
  );
}
